apiVersion: v1
kind: Secret
metadata:
  name: billing-service-secrets
  namespace: fiap-garage
type: Opaque
stringData:
  mongodb-uri: mongodb://mongodb-billing-service:27017/billing_service
  mercadopago-access-token: dummy-token
  mercadopago-public-key: dummy-key
---
apiVersion: v1
kind: Secret
metadata:
  name: execution-service-secrets
  namespace: fiap-garage
type: Opaque
stringData:
  database-user: postgres
  database-password: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: os-service-secrets
  namespace: fiap-garage
type: Opaque
stringData:
  database-user: postgres
  database-password: postgres
